#include "parser/parser_helpers.h"
#include "ast/ast.h"
#include "lexer/token.h"

#define AST_BINARY_OFFSET (AST_BINARY_REM - ACU_TOKEN_PERCENT)
#define AST_UNARY_OFFSET (AST_UNARY_PLUS - ACU_TOKEN_PLUS)
#define AST_ASSIGN_OFFSET (AST_ASSIGN_EQ - ACU_TOKEN_EQUAL)

_Static_assert((AST_BINARY_ADD - ACU_TOKEN_PLUS) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_SUB - ACU_TOKEN_MINUS) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_MUL - ACU_TOKEN_STAR) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_POW - ACU_TOKEN_STAR_STAR) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_DIV - ACU_TOKEN_SLASH) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_REM - ACU_TOKEN_PERCENT) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_BITWISE_AND - ACU_TOKEN_BITWISE_AND) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_BITWISE_OR - ACU_TOKEN_BITWISE_OR) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_BITWISE_XOR - ACU_TOKEN_CIRCUMFLEX) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_SHL - ACU_TOKEN_SHIFT_LEFT) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_SHR - ACU_TOKEN_SHIFT_RIGHT) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_LT - ACU_TOKEN_LANGLE) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_LTE - ACU_TOKEN_LESS_THAN_OR_EQUALS) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_GT - ACU_TOKEN_RANGLE) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_GTE - ACU_TOKEN_GREATER_THAN_OR_EQUALS) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_EQ - ACU_TOKEN_EQUAL_EQUAL) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_NEQ - ACU_TOKEN_NOT_EQUAL) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_LOGICAL_AND - ACU_TOKEN_LOGICAL_AND) == AST_BINARY_OFFSET, "");
_Static_assert((AST_BINARY_LOGICAL_OR - ACU_TOKEN_LOGICAL_OR) == AST_BINARY_OFFSET, "");

_Static_assert((AST_UNARY_BITWISE_NOT - ACU_TOKEN_TILDA) == AST_UNARY_OFFSET, "");
_Static_assert((AST_UNARY_LOGICAL_NOT - ACU_TOKEN_EXCLAMATION_MARK) == AST_UNARY_OFFSET, "");
_Static_assert((AST_UNARY_PLUS - ACU_TOKEN_PLUS) == AST_UNARY_OFFSET, "");
_Static_assert((AST_UNARY_MINUS - ACU_TOKEN_MINUS) == AST_UNARY_OFFSET, "");

_Static_assert((AST_ASSIGN_EQ - ACU_TOKEN_EQUAL) == AST_ASSIGN_OFFSET, "");
_Static_assert((AST_ASSIGN_ADD_EQ - ACU_TOKEN_PLUS_EQUAL) == AST_ASSIGN_OFFSET, "");
_Static_assert((AST_ASSIGN_SUB_EQ - ACU_TOKEN_MINUS_EQUAL) == AST_ASSIGN_OFFSET, "");
_Static_assert((AST_ASSIGN_MUL_EQ - ACU_TOKEN_STAR_EQUAL) == AST_ASSIGN_OFFSET, "");
_Static_assert((AST_ASSIGN_POW_EQ - ACU_TOKEN_STAR_STAR_EQUAL) == AST_ASSIGN_OFFSET, "");
_Static_assert((AST_ASSIGN_DIV_EQ - ACU_TOKEN_SLASH_EQUAL) == AST_ASSIGN_OFFSET, "");
_Static_assert((AST_ASSIGN_REM_EQ - ACU_TOKEN_PERCENT_EQUAL) == AST_ASSIGN_OFFSET, "");
_Static_assert((AST_ASSIGN_BITWISE_AND_EQ - ACU_TOKEN_BITWISE_AND_EQUAL) == AST_ASSIGN_OFFSET, "");
_Static_assert((AST_ASSIGN_BITWISE_OR_EQ - ACU_TOKEN_BITWISE_OR_EQUAL) == AST_ASSIGN_OFFSET, "");
_Static_assert((AST_ASSIGN_BITWISE_XOR_EQ - ACU_TOKEN_CIRCUMFLEX_EQUAL) == AST_ASSIGN_OFFSET, "");
_Static_assert((AST_ASSIGN_SHL_EQ - ACU_TOKEN_SHIFT_LEFT_EQUAL) == AST_ASSIGN_OFFSET, "");
_Static_assert((AST_ASSIGN_SHR_EQ - ACU_TOKEN_SHIFT_RIGHT_EQUAL) == AST_ASSIGN_OFFSET, "");

attribute_const AstBinaryKind AstBinaryKind_FromTokenType(AcuTokenType type) {
    return (AstBinaryKind)(type + AST_BINARY_OFFSET);
}

attribute_const AstUnaryKind AstUnaryKind_FromTokenType(AcuTokenType type) {
    return (AstUnaryKind)(type + AST_UNARY_OFFSET);
}

attribute_const AstAssignKind AstAssignKind_FromTokenType(AcuTokenType type) {
    return (AstAssignKind)(type + AST_ASSIGN_OFFSET);
}
